export enum MissionsType {
  CUSTOM,
  JOIN_WAITLIST,
  DAILY_CHECKIN,
  WEEKLY_CHECKIN,
  REFERRAL,
  SOCIAL,
  FIRST_SHARE,
  MINT_TICKET,
  SHAKING,
  SEND_LUCKY_BOX,
}

export type MissionType = "FIRST_SHARE" | "JOIN_WAITLIST";
